[Loader]
; Enable logging output to the log file (true/false)
EnableLogging=true

; The directory name where mods are located (relative to the game folder)
ModsDirectory=mods

; The directory name where DLL plugins are located (relative to the game folder)
PluginsDirectory=plugins

; The name of the log file to generate
LogFile=mods_loader_log.txt
